name: CI

on:
  push:
  
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        shell: bash
        run: |
          echo "VERSION_PATTERN=$VERSION_PATTERN_NODE" >> "$GITHUB_ENV"
        env:
          VERSION_PATTERN_NODE: '^\s*"version": "(\d+\.\d+\.\d+)".*$'
          VERSION_PATTERN_SBT: 'ThisBuild / version := "(\d+\.\d+\.\d+)"'
  two:
    if: true
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
  three:
    needs:
      - one
      - two
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        shell: bash
        run: |
          echo "$VERSION_PATTERN"
